INSERT INTO BLOBER_TEST (ID) VALUES (1);
INSERT INTO CLOBER_TEST (ID) VALUES (1);

INSERT INTO BLOBER_TEST (ID) VALUES (2);
INSERT INTO CLOBER_TEST (ID) VALUES (2);

INSERT INTO BLOBER_TEST (ID) VALUES (3);
INSERT INTO CLOBER_TEST (ID) VALUES (3);

COMMIT
/

EXIT
/

